// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your_api_key_here',
    appId: '1:719162286540:web:946b5fa21022e525a37d69',
    messagingSenderId: '719162286540',
    projectId: 'laptop-harbour-db',
    authDomain: 'laptop-harbour-db.firebaseapp.com',
    storageBucket: 'laptop-harbour-db.appspot.com',
    measurementId: 'G-JL8MMSYPL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your_api_key_here',
    appId: '1:719162286540:android:16a38048d9553938a37d69',
    messagingSenderId: '719162286540',
    projectId: 'laptop-harbour-db',
    storageBucket: 'laptop-harbour-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your_api_key_here',
    appId: '1:719162286540:ios:43a0adb1802bc1d0a37d69',
    messagingSenderId: '719162286540',
    projectId: 'laptop-harbour-db',
    storageBucket: 'laptop-harbour-db.appspot.com',
    iosBundleId: 'com.example.laptopHarborApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your_api_key_here',
    appId: '1:719162286540:ios:43a0adb1802bc1d0a37d69',
    messagingSenderId: '719162286540',
    projectId: 'laptop-harbour-db',
    storageBucket: 'laptop-harbour-db.appspot.com',
    iosBundleId: 'com.example.laptopHarborApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your_api_key_here',
    appId: '1:719162286540:web:b8cdb9c430b036e9a37d69',
    messagingSenderId: '719162286540',
    projectId: 'laptop-harbour-db',
    authDomain: 'laptop-harbour-db.firebaseapp.com',
    storageBucket: 'laptop-harbour-db.appspot.com',
    measurementId: 'G-P4GB59PLEG',
  );

}